# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190301_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=32)),
                ('image', models.FileField(upload_to='image')),
                ('recommend', models.ManyToManyField(to='api.FreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('level', models.CharField(choices=[(0, '铜牌'), (1, '银牌'), (2, '金牌')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='period',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='freecourse',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CourseDetail'),
        ),
        migrations.AddField(
            model_name='freecourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
        migrations.AddField(
            model_name='lightcourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
    ]
